/**
 * Fortune cookie texts for !cookie. Written for this bot; supibot's own list is
 * AGPL-licensed data and isn't copied here.
 */
export const FORTUNES: readonly string[] = [
  'A pleasant surprise is waiting for you.',
  'Your hard work is about to pay off.',
  'Now is a good time to try something new.',
  'Someone in this chat is thinking about you.',
  'You will soon be the main character.',
  'The best time to touch grass was yesterday. The next best time is today.',
  'A small act of kindness will come back to you.',
  'Do not trust the next person who says "trust me".',
  'Your luck changes when you stop checking it.',
  'An old friend will reach out soon.',
  'Good things come to those who lurk.',
  'You will laugh until it hurts this week.',
  'The answer you seek is in the VOD.',
  'Fortune favours the bold, not the all-in.',
  'You are one decision away from a better day.',
  'Beware of free Kicks from strangers.',
  'Today is a good day to say thank you.',
  'You will make someone smile without trying.',
  'A new adventure starts with a single message.',
  'The chat believes in you, mostly.',
  'Rest is productive too.',
  'Your next idea is better than your last.',
  'Patience now, rewards later.',
  'What you give away comes back doubled.',
  'You already know what to do.',
  'Hydrate. The cookie insists.',
  'Your streak of bad luck ends today.',
  'Something you lost will turn up.',
  'Someone admires your chat game.',
  'Big plans need small first steps.',
  'The quiet ones in chat notice everything.',
  'A stranger will teach you something useful.',
  'You will find what you need where you least expect it.',
  'The shortest answer is often the right one.',
  'Your future self will thank you for going to bed.',
  'Do the boring thing first. The fun thing tastes better after.',
  'A good laugh is worth more than a good argument.',
  'The next clip will be legendary.',
  'You will beat a personal record soon.',
  'Your kindness is louder than you think.',
  'Luck is preparation wearing a disguise.',
  'Say yes to the next small adventure.',
  'The snack you are thinking about is a good idea.',
  'A friend needs your advice more than your opinion.',
  'You are more ready than you feel.',
  'Tomorrow brings a second chance at today.',
  'Your curiosity will lead you somewhere good.',
  'The best gifts cannot be wrapped.',
  'Keep going. The plot twist is coming.',
  'You will hear good news from far away.',
  'Every expert was once a beginner who kept typing.',
  'You will be remembered for your good vibes.',
  'An unexpected message will brighten your day.',
  'A calm mind wins more games than fast hands.',
  'Choose the chair with the best view.',
  'Let the small things go and the big things will follow.',
  'Your laugh is contagious. Use it wisely.',
  'Treat yourself today. You earned it.',
  'A door you thought was closed is only stuck.',
  'Help someone today and forget you did.',
  'The stars are aligned, and so is your posture. Sit up straight.',
  'Good company makes any stream better.',
  'Your gut is right more often than you admit.',
  'You will soon discover a hidden talent.',
  'A little chaos keeps life interesting.',
  'The best view comes after the hardest climb.',
  'Plan less, notice more.',
  'Money comes and goes. Memes are forever.',
  'You are the reason someone logged in today.',
  'Your wildest idea is worth writing down.',
  'Somebody wants to share a secret with you.',
  'A long journey begins with finding your charger.',
  'Take the scenic route this week.',
  'Fortune smiles on those who say hi first.',
  'A mistake today becomes a story tomorrow.',
  'The universe owes you one. Collect it soon.',
  'You will win an argument by not having it.',
  'Good things are brewing. Maybe tea.',
  'An open mind is a full pocket.',
  'You will soon receive something you did not ask for.',
  'Your energy lights up the room, or at least the chat.',
  'Stay humble, stay hungry, stay hydrated.',
  'A clever idea will visit you in the shower.',
  'Silence is golden. Muted mics are platinum.',
  'Spend time on what makes time disappear.',
  'Someone will ask you for directions. Know the way.',
  'A shared joke is a friendship started.',
  'Believe in the plan, but keep a backup plan.',
  'Your patience will be rewarded, probably with more waiting.',
  'Be the reason someone keeps their streak.',
  'Your next purchase will be worth it.',
  'Adventure is out there, just past the loading screen.',
  'A hug is coming your way.',
  'The best is yet to come, and it is almost here.',
  'Luck is on your side today. Use it before it logs off.',
  'An honest compliment will change someone\'s day.',
  'There is wisdom in taking a nap.',
  'You will soon laugh at what worries you now.',
  'A small win today leads to a big one tomorrow.',
  'Trust your aim.',
  'You will find a coin on the ground. Keep it.',
  'Life is a stream. Do not forget to hit record.',
  'The cookie is small but its advice is large.',
  'Someone will copy your style. Take it as a compliment.',
  'Your future holds many good snacks.',
  'Do something today your past self would be proud of.',
  'The fish are biting. Go cast a line.',
  'A good friend is the best loot drop.',
  'You will soon be invited somewhere fun.',
  'Nothing is impossible. Some things are just very unlikely.',
  'Pay attention to the next song you hear.',
  'Cheer for someone else\'s win today.',
  'You will outlast the lag.',
  'A lucky number will appear to you three times.',
  'The early bird gets the worm. The late bird gets the VOD.',
  'Smile at the next person who types in chat.',
  'You will conquer the thing you keep putting off.',
  'Great minds think alike. Weird minds think better.',
  'Your ideas are worth sharing out loud.',
  'A surprise gift is closer than you think.',
  'Every day is a new save file.',
  'You will soon be the MVP of something.',
  'Keep your friends close and your snacks closer.',
  'Kindness is free. Spam it.',
  'You are exactly where you need to be.',
  'The algorithm favours you today.',
  'A small detour will lead to a great discovery.',
  'Learn one new thing today and teach it tomorrow.',
  'Your worries are smaller than they look.',
  'This cookie was baked with luck. Chew slowly.',
  'The chat will remember this moment.',
  'Good vibes attract good people.',
  'Your next gamble... just kidding. Save your points.',
  'Change your perspective and the problem shrinks.',
  'An old hobby will bring new joy.',
  'Someone will laugh at your joke tomorrow.',
  'Take the compliment. You deserve it.',
  'Do not count your wins before they are clipped.',
  'Fortune favours the curious.',
  'Your best moment this week has not happened yet.',
  'Wear the lucky socks.',
  'A kind word today saves a friendship tomorrow.',
  'The cookie crumbles, but your spirit does not.',
  'The next cookie will be even better.'
];
